title: Settings
data:
  site_name: 'Paul Keys Portfolio'
  social:
    -
      id: 8eNDiQyA
      name: Twitter
      url: 'https://twitter.com/jackmcdade'
      icon: site/social-icons/twitter.svg
    -
      id: YDBrFy3r
      name: Github
      url: 'https://github.com/statamic/starter-kit-cool-writings'
      icon: site/social-icons/github.svg
    -
      id: UqFUCbm6
      name: Email
      url: 'mailto:jack@statamic.com'
      icon: site/social-icons/email.svg
  description: 'this is the portfolio of a super awesome 3d artist'
  og_title: 'Paul Keys Portfolio'
  og_description: 'this is the og description of a portfolio of a super awesome 3d artist'
  og_image: 000024.JPG
