tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: blocks
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    content:
                      display: Content
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: content
                          field:
                            buttons:
                              - h2
                              - h3
                              - bold
                              - italic
                              - unorderedlist
                              - orderedlist
                              - removeformat
                              - quote
                              - anchor
                              - image
                              - table
                              - code
                              - codeblock
                              - alignleft
                              - aligncenter
                              - alignright
                              - alignjustify
                            smart_typography: false
                            save_html: false
                            inline: false
                            toolbar_mode: fixed
                            reading_time: false
                            word_count: false
                            fullscreen: true
                            allow_source: true
                            enable_input_rules: true
                            enable_paste_rules: true
                            remove_empty_nodes: false
                            antlers: false
                            link_noopener: false
                            link_noreferrer: false
                            target_blank: false
                            always_show_set_button: false
                            collapse: false
                            previews: true
                            type: bard
                            display: Content
                            icon: bard
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                    image:
                      display: Image
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: image
                          field:
                            max_files: 1
                            mode: list
                            container: assets
                            restrict: false
                            allow_uploads: true
                            show_filename: true
                            show_set_alt: true
                            type: assets
                            display: Image
                            icon: assets
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                    video:
                      display: Video
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: video
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: Video
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
              type: replicator
              display: Blocks
              icon: replicator
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              mode: single
              inline: false
              full_width: false
              columns: 1
              rows: 1
              time_enabled: false
              time_seconds_enabled: false
              display: Date
              icon: date
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
              validate:
                - required
          -
            handle: stack
            field:
              type: terms
              taxonomies:
                - stack
              display: stack
              mode: select
              create: true
              icon: taxonomy
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
title: Project
